/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "accent-neon": "#E8FF66",
              "surface-tint": "#5f5e5e",
              "on-tertiary-fixed-variant": "#3e4942",
              "inverse-on-surface": "#f0f1f1",
              "surface-container-highest": "#e2e2e2",
              "surface-container-lowest": "#ffffff",
              "on-primary-container": "#858383",
              "primary": "#000000",
              "on-tertiary": "#ffffff",
              "secondary-fixed-dim": "#bcd13d",
              "error-container": "#ffdad6",
              "on-primary-fixed-variant": "#474646",
              "on-tertiary-fixed": "#141e18",
              "tertiary": "#000000",
              "on-secondary-fixed-variant": "#414b00",
              "on-secondary": "#ffffff",
              "error": "#ba1a1a",
              "primary-fixed-dim": "#c8c6c5",
              "tertiary-fixed-dim": "#bec9c0",
              "outline": "#747878",
              "on-error-container": "#93000a",
              "on-tertiary-container": "#7b877e",
              "surface-variant": "#e2e2e2",
              "primary-fixed": "#e5e2e1",
              "surface-container-high": "#e8e8e8",
              "surface-dim": "#dadada",
              "surface-bright": "#f9f9f9",
              "background": "#DCE8DE",
              "on-primary": "#ffffff",
              "accent-peach": "#FFD7C7",
              "surface": "#f9f9f9",
              "on-secondary-container": "#5d6b00",
              "on-surface": "#1a1c1c",
              "secondary-container": "#d7ee57",
              "on-secondary-fixed": "#191e00",
              "secondary": "#586400",
              "secondary-fixed": "#d7ee57",
              "on-background": "#1a1c1c",
              "surface-container": "#eeeeee",
              "surface-container-low": "#f3f3f4",
              "card-lavender": "#DCD5FF",
              "inverse-primary": "#c8c6c5",
              "text-secondary": "#777777",
              "on-primary-fixed": "#1c1b1b",
              "on-surface-variant": "#444748",
              "sidebar-matte": "#111111",
              "card-coral": "#FFD3D3",
              "primary-container": "#1c1b1b",
              "tertiary-fixed": "#dae6dc",
              "outline-variant": "#c4c7c7",
              "card-mint": "#D8F5E8",
              "inverse-surface": "#2f3131",
              "on-error": "#ffffff",
              "tertiary-container": "#141e18"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "card-custom": "28px",
              "full": "9999px"
      },
      "spacing": {
              "unit": "8px",
              "gap-xl": "64px",
              "gap-md": "24px",
              "container-padding": "40px",
              "sidebar-width": "280px"
      },
      "fontFamily": {
              "headline-md": ["Hanken Grotesk"],
              "label-mono": ["JetBrains Mono"],
              "headline-lg": ["Hanken Grotesk"],
              "headline-lg-mobile": ["Hanken Grotesk"],
              "body-lg": ["Inter"],
              "body-md": ["Inter"],
              "display-xl": ["Hanken Grotesk"]
      },
      "fontSize": {
              "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "label-mono": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
              "headline-lg": ["48px", {"lineHeight": "52px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-lg-mobile": ["32px", {"lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "display-xl": ["84px", {"lineHeight": "90px", "letterSpacing": "-0.04em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [],
}
